# Generated by Django 5.0 on 2024-01-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiftlytasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
