# Generated by Django 5.0 on 2024-01-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('swiftlytasks', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='CustomPermission',
        ),
    ]
